### ISSUE TITLE
Request for enhancement

### ISSUE THREAD

**Issue by P1119r1m** [Samsung/CredSweeper#116]
I think that the algorithm of its work should be revised.
For example, the utility reported 157 results.
There are mostly false alarms:
```
TEEC_ERROR_COMMUNICATIONPASSTEEC_ERROR_SHORT_BUFFERANY_OWNER_SETFAILInvoke_1param_valueInOuthexdump[%zu]:TEEC_InitializeContext
Test passedERROR : TEEC_InvokeCommand failed: %s.
Test passed.%s: OpenSession failed: %x.
# Pass Cond   : TEE_SUCCESS
# Pass Cond    : Passed if unit_tzld passes
Test passedERROR : TEEC_InvokeCommand failed: %s.
 # Pass Cond    : Passed if average time.
[swd_tzisr_test] TESTING : Thread 1:0x%08x:PASS:0x%08x
[swd_tzisr_test] TESTING : 0x%08x:PASS:0x%08x
cpuid[swd_tzisr_test] TESTING : Main Thread :0x%08x:PASS:0x%08x
TEEC_ERROR_COMMUNICATIONPASSTEEC_ERROR_SHORT_BUFFERANY_OWNER_SETFAILhexdump[%zu]:TEEC_InitializeContext
Test failedTest passedERROR: attack test failed: '%s' from '%s'.
```

Such "creds" were found in a binary file.
I haven't checked source codes of this repo, but there is a feeling that I will find there something like:
```
strings BINARY_FILE | grep -i "pass"
```

There have also been reports  of this utility reporting "creds" found in the "DRM"ed (read encrypted) documents.

Dear maintainers, please consider the cases of false positives in order to improve its performance.

Thank you!

**Comment by babenek** [comment]
Did you enabled '--ml_validation' ?
Could you provide command line (or how exactly) you had run the tool?
And if possibly - the data which you tested with false-positive credentials (extension of the file?).

**Comment by meanrin** [comment]
> Our organization doesn't use '--ml_validation' option.

Please conciser using `--ml_validation` if possible, as it the main feature differentiating this scanner from other alternatives 

_Validation by [ML model classifier](https://credsweeper.readthedocs.io/en/latest/overall_architecture.html#ml-validation) is used to reduce False Positives (by far), but might increase False negatives and execution time. So –ml_validation is recommended, unless you want to minimize FN._ [doc link](https://credsweeper.readthedocs.io/en/latest/guide.html)

However, we would take a look at working with binaries, thanks for the description!

**Comment by P1119r1m** [comment]
> Please conciser using `--ml_validation` if possible, as it the main feature differentiating this scanner from other alternatives
Thank you for this advice! We will check this option.
 
> However, we would take a look at working with binaries, thanks for the description!
It would be great. Thanks!

**Comment by wcshim40** [comment]
Considering the issue [126](https://github.com/Samsung/CredSweeper/issues/126) and the number of false-positive reports, it would be better to default ml_validation. 

In addition, I heard from someone complaining about FPs due to the XML attributes name (e.g., `<tool RefKey='DVmaxTimeTool" Name="ETD"/>`) and the [test certificates](https://github.com/openssl/openssl/tree/master/test/certs) from open source projects. 

@csh519, could you share your thoughts on this?

**Comment by csh519** [comment]
@wcshim40 
I think it would be good to set `ml_validation` option as default too.
Actually we already discussed this issue in our inner github, i'll share the link by messanger.

**Comment by csh519** [comment]
I close this issue and we'll handle `ml_validation` option as default on #126.
