### ISSUE TITLE
Enable ml_validation by default

### ISSUE THREAD

**Issue by babenek** [Samsung/CredSweeper#126]
Side effect of binary files scanning is many false-positive cases without --ml_validation.
Users might use minimal set of arguments (e.g. '--path' only). 
It leads to big false-positive warnings due binary files are decoded like Latin1 text. 
Evidently, random ASCII bytes look like a good password. Thus '--ml_validation' filters many of the warnings.

Enabling the option supposes to install ML library by default.

**Comment by csh519** [comment]
As we discussed, I'll create a PR that defaults to `ml_validation` option.
It might be done before next week.
