### ISSUE TITLE
VCS checks fail on main branch

### ISSUE THREAD

**Issue by csh519** [Samsung/CredSweeper#127]
[VCS checks](https://github.com/Samsung/CredSweeper/blob/881b688d96f2dca3e8b60c29d4b244a6e7d93ad9/.github/workflows/vcs.yml) is continuously failing.

@babenek could you please check this issue?

**Comment by csh519** [comment]
I think it occurred below code block.
It seems `github.event.pull_request.base.repo.releases_url` return empty string when PR merged.
So it would be better make other option or fix running condition of checks i think.

https://github.com/Samsung/CredSweeper/blob/881b688d96f2dca3e8b60c29d4b244a6e7d93ad9/.github/workflows/vcs.yml#L29-L34

**Comment by babenek** [comment]
It might fail in forked repositories due they have no releases.
You can fix it with creating personal release in your fork e.g. for version 1.3.0.
Note: 1.1.0 is not suitable due has parallel branch.
I fixed with dummy release from initial commit for my fork.

**Comment by csh519** [comment]
Oh It was not regarding forked repositories, it occurs in main branch of CredSweeper.
[VCS checks](https://github.com/Samsung/CredSweeper/blob/881b688d96f2dca3e8b60c29d4b244a6e7d93ad9/.github/workflows/vcs.yml)
