### ISSUE TITLE
Handle Key category FPs and test certs

### ISSUE THREAD

**Issue by csh519** [Samsung/CredSweeper#142]
There was a suggestion about reducing the FP of items caught in the `Key` category as below and not detecting items that are test certificates.

@wcshim40  https://github.com/Samsung/CredSweeper/issues/116#issuecomment-1158291551
> In addition, I heard from someone complaining about FPs due to the XML attributes name (e.g., `<tool RefKey='DVmaxTimeTool" Name="ETD"/>`) and the [test certificates](https://github.com/openssl/openssl/tree/master/test/certs) from open source projects.

-----------

### Reducing the FP `Key` category.
It seems the FP line(`<tool RefKey='DVmaxTimeTool" Name="ETD"/>`) should be filtered by [ValueDictionarykeywordCheck](https://github.com/Samsung/CredSweeper/blob/main/credsweeper/filters/value_dictionary_keyword_check.py).
But it wasn't, and when I looked more, the keywords `max`, `Time`, `Tool` aren't included in [keyword_checklist.txt](https://github.com/Samsung/CredSweeper/blob/main/credsweeper/common/keyword_checklist.txt).
There were similar keywords like `maximum`, `timer`, `tools`, and so on...
So I think it would be good to add those keywords(`max`, `Time`, `Tool`) in [keyword_checklist.txt](https://github.com/Samsung/CredSweeper/blob/main/credsweeper/common/keyword_checklist.txt).

### Exclude test certificates. (like openssl and so on)
1. Make list of test cretificates. (It may take a long time to do this)
2. Generate file hash of each test certifiactes.
    - I think if we compare the test certificates with path or name, FP will increase. So it will be good to use file hash and path at the same time.
3. Store that file hashes in the CredSweeper.

**Comment by babenek** [comment]
Why certificates, which are are public by itself, are an issue?
Did you mean "private keys"?

**Comment by csh519** [comment]
@babenek 
Yes, there are private keys for testing on some open sources. (https://github.com/openssl/openssl/tree/master/test/certs)

**Comment by csh519** [comment]
There is still problem on test certs.. but I solved FP line(`<tool RefKey='DVmaxTimeTool" Name="ETD"/>`) with adding XML parser(#193).
