### ISSUE TITLE
need an excutable binary

### ISSUE THREAD

**Issue by taejun45** [Samsung/CredSweeper#169]
hello, 
I need to checkup a system for Key,Credential.

It's a very simple system, and 
if you provide .exe and linux util, 
It must be very convenient and easy for all . 

please support a simple executable pkg

**Comment by babenek** [comment]
Hello.
CredSweeper is installed as util already. 
If you use system python3.(8-9) interpreter - then you can launch ```credsweeper``` in command line 
https://github.com/Samsung/CredSweeper/blob/279a424e180155d6a07346c2942d9f7883fb76ba/.github/workflows/test.yml#L49

**Comment by csh519** [comment]
@taejun45 
Hello.
If it is about Samsung internal issue, please use voc page or mail to me.

Thank you.
