### ISSUE TITLE
Possible improvements for documentation

### ISSUE THREAD

**Issue by meanrin** [Samsung/CredSweeper#18]
Improvement points for our project
Left by few other people already doing opensource in Samsung

1. Add contribution document with Exact step-by-step description on how to create a new PR ( [example](https://github.com/Samsung/ONE/blob/master/docs/howto/how-to-contribute.md) )
2. Add link to MIT license official site in all places where we mention it
3. Edit install/run/tests examples in the Readme, such that code can be copied and executed without any change
(currently we have some lines that start from # or $ that should be manually removed)
4. Add `pull-request-template.md`

All this is just opinion/advice

**Comment by csh519** [comment]
I agree with all your suggestions!
Regarding number 2. do you mean we should add MIT license link on all `.md` files?

**Comment by meanrin** [comment]
> I agree with all your suggestions! Regarding number 2. do you mean we should add MIT license link on all `.md` files?

I meant the line `The CredSweeper is an Open Source project released under the terms of MIT License V2.` here in readme:
https://github.com/Samsung/CredSweeper#license

**Comment by csh519** [comment]
@meanrin 

> > I agree with all your suggestions! Regarding number 2. do you mean we should add MIT license link on all `.md` files?
> 
> I meant the line `The CredSweeper is an Open Source project released under the terms of MIT License V2.` here in readme: https://github.com/Samsung/CredSweeper#license

Oh.. It was missed. I think it would be good to add.
