### ISSUE TITLE
Not working without error

### ISSUE THREAD

**Issue by securekim** [Samsung/CredSweeper#180]
I entered the following command, but I don't know if it worked.

_python -m credsweeper --path {MY_SRC_PATH} --save-json cred.json_

I opened the result file (cred.json), but there was only an empty array.

I added some credential strings for test. But nothing has changed.

Please help me.

**Comment by csh519** [comment]
Hello.

I think CredSweeper executed successfully and there is no credential scanned.
So the json file has empty array only.

And regrading credential string testing, I don't know which credential did you tested.
But you can find out it works easily with below string.

``` text
password = "qazwsxedc1@"
```

*It just sample password.*

**Comment by securekim** [comment]
안녕하세요.
그것은 동작합니다.
하지만 당시에 아래의 테스트는 동작하지 않았습니다.
password="This_Is_Real_Password"

이 테스트가 왜 검출되지 않았는지 사실과 별개로, 이것이 실제로 일을 잘 수행 하고 있는지 알고 싶습니다.
그러기 위해서는 테스트를 실제로 몇개 수행 하였는지에 대한 내용을 표시해야 합니다.

**Comment by csh519** [comment]
You can enable logging with `-l debug` option, and then you can see how CredSweeeper is work.
And also you can get info about why the credentials that you made is filtered.

BTW showing scanned total file count is good feature. I'll make a change regarding this.

Thank you.
