### ISSUE TITLE
Argument --depth and workaround

### ISSUE THREAD

**Issue by babenek** [Samsung/CredSweeper#192]
The issue was created due #183 has to  add second workaround to remove `.gz `extension from excluded list. First was `.zip`.
The argument `--depth` enables file analysis not like plain text but with recursion if the file is an archive. 
Thus, class FilePathExtractor works **before** the analysis and removes true zip archives by extension. So, the feature might look like malfunction.
Suppose, -`-depth` will analyse various file types by content and the exclude list will be ignored.
Simultaneously excluding by `not_allowed_path_pattern` and others are working before the list exluding.
https://github.com/Samsung/CredSweeper/blob/eec642f420a3d27ff0e81489e1e01d61abb980bd/credsweeper/file_handler/file_path_extractor.py#L127-L135

**Comment by babenek** [comment]
My proposal is to skip file extension when `--depth`` is enabled due other approach to exclude for file extension are still available.

**Comment by babenek** [comment]
+ proposal :
Add __init__ method  CredSweeper ( Config )

**Comment by csh519** [comment]
I think we've already added `--depth` option aren't we?

Could you please check this issue and if it has been merged, please close this issue.
