### ISSUE TITLE
Regarding release new version of CredSweeper.

### ISSUE THREAD

**Issue by csh519** [Samsung/CredSweeper#221]
Still we(@Samsung/credsweeper_maintainers ) just release new version of CredSweeper anytime we feel like it.
I think it would be good to decide how to release new version and here is suggestions.

### Suggestions
**1. Anytime we feel like it.**
**2. Set period like 'once in a month'.**

Please let me know your opinions by comment.

Thank you.

**Comment by kmnls** [comment]
By demand, after update

**Comment by csh519** [comment]
@babenek 

Okay.. but.. how about 2 weeks for duration?
1 week is too short I think.
