### ISSUE TITLE
CredSweeper not detecting google_multi

### ISSUE THREAD

**Issue by Riddle1001** [Samsung/CredSweeper#266]
I just installed CredSweeper, and I tested

`python -m credsweeper --path google_multi `

And google_multi has the contents of
```
012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com

4L2QMyTm6Rr0o46ytGiReoG1

```

But when I run it, I get

```
Detected Credentials: 0
Time Elapsed: 0.11600160598754883s
```

But if I run the password test sample I get the expected output

```
python -m credsweeper --path password
rule: Password / severity: medium / line_data_list: [line: 'password = "cackle!"' / line_num: 1 / path: password / value: 'cackle!' / entropy_validation: False] / api_validation: NOT_AVAILABLE / ml_validation: VALIDATED_KEY
Detected Credentials: 1
Time Elapsed: 0.11830568313598633s
```

Perhaps i'm doing something wrong?

**Comment by csh519** [comment]
Hello.

Thank you for question.

I tried it too and i got same result as you saw..

``` bash
$ python -m credsweeper --path tests/samples/google_multi 
Detected Credentials: 0
Time Elapsed: 0.12809443473815918s
```

So I checked why it filtered and found out the reason.

``` bash
2023-02-13 11:21:32,397 | DEBUG | ml_validator:160 | ML decision: False with prediction: 0.001 for value: 012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com
```

CredSweeper has ML validation logic and it filtered the line.
Actually google multi sample was added before ML validation feature, so it can be filtered.

And you can check expected result with `--ml_threshold 0` option.

``` bash
$ python -m credsweeper --path tests/samples/google_multi --ml_threshold 0
rule: Google Multi / severity: high / line_data_list: [line: '012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com' / line_num: 2 / path: tests/samples/google_multi / value: '012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com' / entropy_validation: True, line: '4L2QMyTm6Rr0o46ytGiReoG1' / line_num: 4 / path: tests/samples/google_multi / value: '4L2QMyTm6Rr0o46ytGiReoG1' / entropy_validation: False] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
Detected Credentials: 1
Time Elapsed: 0.07845592498779297s
```

**Comment by Riddle1001** [comment]
> Hello.
> 
> Thank you for question.
> 
> I tried it too and i got same result as you saw..
> 
> ```shell
> $ python -m credsweeper --path tests/samples/google_multi 
> Detected Credentials: 0
> Time Elapsed: 0.12809443473815918s
> ```
> 
> So I checked why it filtered and found out the reason.
> 
> ```shell
> 2023-02-13 11:21:32,397 | DEBUG | ml_validator:160 | ML decision: False with prediction: 0.001 for value: 012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com
> ```
> 
> CredSweeper has ML validation logic and it filtered the line. Actually google multi sample was added before ML validation feature, so it can be filtered.
> 
> And you can check expected result with `--ml_threshold 0` option.
> 
> ```shell
> $ python -m credsweeper --path tests/samples/google_multi --ml_threshold 0
> rule: Google Multi / severity: high / line_data_list: [line: '012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com' / line_num: 2 / path: tests/samples/google_multi / value: '012-GiReoGiGiReoGiGiReoGiGiReoGi1230.apps.googleusercontent.com' / entropy_validation: True, line: '4L2QMyTm6Rr0o46ytGiReoG1' / line_num: 4 / path: tests/samples/google_multi / value: '4L2QMyTm6Rr0o46ytGiReoG1' / entropy_validation: False] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
> Detected Credentials: 1
> Time Elapsed: 0.07845592498779297s
> ```

Ah okay, I understand, that makes sense. Thanks for the quick reply and clearing it up for me.
