### ISSUE TITLE
Question: Excluding Specific Files from CredSweeper Analysis

### ISSUE THREAD

**Issue by numairmansur** [Samsung/CredSweeper#358]
Hi, 

Thanks for the great work! 
I'd like to find out if there's a feature that allows me to specify certain files that CredSweeper should not analyze. Specifically, I'm interested in excluding files containing the term "Test" in their names - for instance, a file like `/src/com/github/key/TestKeyProvider.java`

Could you please advise if this is currently possible, or if there's a workaround to achieve this functionality?

Thanks!

**Comment by csh519** [comment]
Hello.

Thank you for a question.

Actually we have a feature which you wanted.
https://github.com/Samsung/CredSweeper/blob/main/credsweeper/secret/config.json#L1-L3

If you want to exclude `test` files, you can add regular expression to `config.json` like below.
``` json
{
    "exclude": {
        "pattern": [
            "(.)*test(.)*"
        ],
...
```

As you know the value of `pattern` is list of regular expression, so you can add other regular expression additionally.



Thank you.

**Comment by numairmansur** [comment]
Ah perfect! Thank you so much and thanks for this amazing work :)
I hope to contribute to this project in the future as well :)
