### ISSUE TITLE
Additional fields to output

### ISSUE THREAD

**Issue by meanrin** [Samsung/CredSweeper#41]
`LineData` object we print as output have much more internal field that we actual output to user
While some of them might be a bit redundant, I think there are few properties that might be useful:

- `variable` - variable name related to the secret
- predicted probability by the ML model. While it's not a property of `LineData` now, it might be saved and outputted to the user

**Comment by csh519** [comment]
The second idea is good! It will be good to add predicted probability into `LineData` as attribute.
BTW I think there can be user who want to configure the output attributes of `LineData`.
So, what about add output option of `LineData` on `secret/config.json` file?

**Comment by csh519** [comment]
Or it can be set by CLI option.
- no option : standard
- `--details` : detailed output
