### ISSUE TITLE
Discrepancy in `value`, `value_start`, and `value_end` in Scan Results

### ISSUE THREAD

**Issue by numairmansur** [Samsung/CredSweeper#452]
Hi,
I've encountered an issue with the scan results related to the indexes of `value_start` and `value_end` not aligning correctly with the `value` field. I found the discrepancy while scanning a URL containing a `Key`. When I scan a file containing the following line with default rules in version `1.5.9`. 
```
https://maps.google.com/maps/api/js?key=wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA&libraries=places
```
The scan yields the following finding: 
```
[
    {
        "api_validation": "NOT_AVAILABLE",
        "ml_validation": "VALIDATED_KEY",
        "ml_probability": 0.9186561107635498,
        "rule": "Key",
        "severity": "medium",
        "line_data_list": [
            {
                "line": "https://maps.google.com/maps/api/js?key=wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA&libraries=places",
                "line_num": 3,
                "path": "test/urls.txt",
                "info": "",
                "value": "wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA",
                "value_start": 40,
                "value_end": 98,
                "variable": "key",
                "entropy_validation": {
                    "iterator": "BASE64_CHARS",
                    "entropy": 4.8854165898713005,
                    "valid": true
                }
            }
        ]
    }
]
```

The value field correctly shows `wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA`. However, the `value_start` and `value_end` indexes do not accurately reflect the start and end of this `value` within the line.
Demonstration using Python:
```
>>> text = "https://maps.google.com/maps/api/js?key=wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA&libraries=places"
>>> print(text[40:98])
'wredzaSyCj4RVnfs3eU72CZXDIB9UG4NRt-VF1yOA&libraries=places'
```

I'm curious to know if this discrepancy is already a known issue. Ideally, the `value` should align precisely with the `value_start`and `value_end` indexes provided in the result. I tired to look at the code but could not figure out why this discrepancy is occurring.

**Comment by babenek** [comment]
Thank you for discovering the issue.
Wrong position appears because the position has been got from regex values but after "sanitize" the value is reduced.
https://github.com/Samsung/CredSweeper/blob/ea2ee9605e8683c7da4c600e9fda491635933db0/credsweeper/credentials/line_data.py#L107
