### ISSUE TITLE
Add the ability to check the version as pkg.__version__

### ISSUE THREAD

**Issue by Dmitriy-NK** [Samsung/CredSweeper#47]
Add to credsweeper.__init__ package version note
Example: https://github.com/Samsung/Universum/blob/master/universum/__init__.py

**Comment by meanrin** [comment]
Version in`__init__` would allow to execute
```python3
import credsweeper
credsweeper.__version__
``` 

That would allow `setup.py` or script for automatic document generation to easily check current package version
It is also a convenient way used by many other libraries to store version inside the package: https://stackoverflow.com/a/20180564

**Comment by meanrin** [comment]
On the other hand: "there appears to be increasing support amongst Python core developers to recommend not including a `__version__` attribute, e.g. in https://gitlab.com/python-devs/importlib_metadata/-/merge_requests/125."
https://stackoverflow.com/a/20180564 

If you already installed credsweeper with pip it's also possible to check version with
```python
>>> from importlib.metadata import version
>>> version('credsweeper')
'1.1.0'
```

**Comment by babenek** [comment]
Please, review https://github.com/Samsung/CredSweeper/pull/122
