### ISSUE TITLE
List all possible outputs in the CLI and docs

### ISSUE THREAD

**Issue by meanrin** [Samsung/CredSweeper#68]
To easier understanding of report and better scanner integration it would be useful to list all possible states in which reported fields can be

For example:
```
rule: str, any value

severity: str
- "critical"
- "high"
- "medium"
- "low"
- "info"

ml_validation: str
- "INVALID_KEY"
- "VALIDATED_KEY"
- "UNDECIDED"
- "NOT_AVAILABLE"

entropy_validation: bool
- true
- false

...
```

Why this is necessary?
For example for now we have `"critical"` severity in code, but no actual rule with this severity
Is we would add a new rule with `"critical"` severity it might brake systems that don't expect severity to be anything else but `high/medium/low/info` 

Where to list?
Good place to mention possible outputs might be CLI `--help` and [how to use doc section](https://credsweeper.readthedocs.io/en/latest/guide.html)

**Comment by csh519** [comment]
Good point.
Actually we don't have list for them. So i think it can be remove or make a list for them.

The severity was created by intuition and it seems useless now. I agree to remove them.
