### ISSUE TITLE
Add minimal severity, additional rules, log config, and config arguments

### ISSUE THREAD

**Issue by meanrin** [Samsung/CredSweeper#69]
Some files in the scanner is modifiable in theory, but is a pain to eddit if package installed using pip

This include: 
- `credsweeper/secret/config.json` - file that lists exclude pats, and what fields should be saved in the final report
- `credsweeper/secret/log.yaml` - file specifies log format, max size of log file if any is used, log file location (none by default), etc

So I propose to add something similar to:
```
--config [PATH]          path of config file (default: credsweeper/secret/config.json)
--log-config [PATH]      path of log config file (default: credsweeper/secret/log.yaml)
```

------------------------

In addition this 2 flags might be useful:

`minimal-severity` can be a useful flag for people who do not want to edit config, but just don't want to see info or low severity alerts

```
--minimal-severity            Hides any report with severity lower than specified. Any of ['info', 'low', 'medium', 'high', 'critical']. Default: info
```

`additional-rules` might allow to add new rules in addition to existing one, without copying base file

```
--additional-rules [PATH]     Add new rules to the one already listed in `credsweeper/rules/config.yaml` without overriding the old one 
```

That would allow us to avoid next scenario:
1. User copied our rule file and manually adds a new rule
2. We edit main rule file (for example fixing old regex or adding new rules) in a next release
3. Now user cannot use our newly edited main rule file, until they manually update their own edited copy 

By adding `additional-rules` that do not override the main one this scenario can be avoided

**Comment by babenek** [comment]
Enhance proposal:
1. put all default values into code when we not use package files. It speedup fuzzing a bit and improve testing.
2. migrate from YAML to JSON
3. add --export_... (log, config, rules) to make a template for user
