### ISSUE TITLE
Suggest basic scanning feature

### ISSUE THREAD

**Issue by wcshim40** [Samsung/CredSweeper#94]
Oftentimes key files can be included in a repository but CredSweeper mainly focuses on the `hard-coded secrets`  in documents. Thus, I'd like to propose a new feature that reports suspicious file extensions such as `.pem , .crt, .cer,  .csr,  .der,  .pfx,  .p12, .key `and` .jks`. Maybe we have to provide an option to turn on/off this feature due to the expected high false positives.

**Comment by kmnls** [comment]
https://code.sec.samsung.net/jira/browse/SASAF-5411
